### Project specific config ###
language: node_js

node_js:
  - '4'
  - '6'

env:
  global:
    - ATOM_LINT_WITH_BUNDLED_NODE="false"

os:
  - linux
  - osx

after_script:
  - npm run lint

### Generic setup follows ###
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

# Needed to disable the auto-install step running `npm install`
install: true

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
